### PR TITLE
Avoid double patch bump

### PR DESCRIPTION
**Pull request by dagguh**

### CODE REVIEW

**Review by pczuj — APPROVED** [review]
I understand those are only changes in tests and those make sense to me.

**Comment by dagguh** [comment]
Yes, the tests show:
* in the first commit, how consumers (like db-replica, aws-infrastructure) were getting double patch bumps
* in the second commit, how they (me) were using `markNextVersion` wrongly and unnecessarily

PS. the CI is red (twice), but locally it's full green. Will take a look tomorrow.

**Comment by dagguh** [comment]
After merging #7, I tried the "rebase" via GH GUI. It worked well, but the commits are no longer signed by me (obviously). I'll re-push my locally signed commits.

**Comment by dagguh** [comment]
The CI failure smells funny, it keeps talking about Gradle 6.7:
```
Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (file:/home/runner/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7/lib/groovy-all-1.3-2.5.12.jar) to constructor java.util.regex.Pattern(java.lang.String,int)
```
But the wrapper is 6.7. I learned that you can [clear the GH caches via GH CLI](https://stackoverflow.com/a/64819132), so I did:
```
» gh cache delete --all
✓ Deleted 10 caches from atlassian-labs/gradle-release
```
Let's see now...

**Comment by dagguh** [comment]
Didn't help. Next I'll try to avoid the deprecated `gradle-build-action`

**Comment by dagguh** [comment]
Also didn't help. BTW I see that 6.7 comes from our test sources, where we explicitly run a test project on Gradle 6.7

**Comment by dagguh** [comment]
It's environmental, maybe JDK version, maybe something else. I'll add build scans to compare them local vs CI.

**Comment by dagguh** [comment]
Yep, CI runs on Java 11, local on 8:

**Comment by dagguh** [comment]
Argh, still [locally green on Java 11](https://scans.gradle.com/s/6aqebjnrcg7g2#infrastructure).
It's `Homebrew OpenJDK Runtime Environment 11.0.23+0` vs `Eclipse Temurin OpenJDK Runtime Environment 11.0.23+9`, but I'll look for a more significant difference.

Hold the phone, I didn't inspect the test failure:
```
java.lang.AssertionError: 	
Expecting file:	
  </home/runner/.m2/repository/com/atlassian/performance/tools/publish-test/0.3.0-SNAPSHOT/publish-test-0.3.0-SNAPSHOT.pom>	
to exist.
```
It's definitely environmental. Suspects:
* `user.home` property assumption is wrong
* my local `~/.m2` is "dirty" and makes the test a false green

**Comment by dagguh** [comment]
After cleaning my `.m2` it repros locally!
```
rm -rf ~/.m2/repository/com/atlassian/performance/tools/publish-test
```
Gotta make the test better isolated from the env.

**Pull request merged**
